In [1]:
import torch
import numpy as np
import pandas as pd


In [8]:
log_data_new = torch.load('./data/params/data_params_20240808-4939.pt')
log_data_new

{'xymean': tensor([[ 1.0179e+00,  2.0130e+01, -1.2196e-02, -5.7562e-02]]),
 'xystd': tensor([[0.0162, 7.9996, 1.2177, 0.8822]]),
 'edgemean': tensor([[3.0359, 0.2727]]),
 'edgestd': tensor([[16.7659,  2.0454]])}

In [2]:
log_data22 = torch.load('/mnt/afs/data/Samples_v5/case118/processed_data/caseN/IEEE118,case0,FL0.pt')
log_data22

HeteroData(
  PQ={ x=[64, 6] },
  PV={ x=[53, 6] },
  Slack={ x=[1, 6] },
  (PQ, default, PQ)={
    edge_index=[2, 70],
    edge_attr=[70, 5],
    edge_pq=[70, 2],
  },
  (PQ, default, PV)={
    edge_index=[2, 93],
    edge_attr=[93, 5],
    edge_pq=[93, 2],
  },
  (PQ, default, Slack)={
    edge_index=[2, 3],
    edge_attr=[3, 5],
    edge_pq=[3, 2],
  },
  (PV, default, PQ)={
    edge_index=[2, 93],
    edge_attr=[93, 5],
    edge_pq=[93, 2],
  },
  (PV, default, PV)={
    edge_index=[2, 104],
    edge_attr=[104, 5],
    edge_pq=[104, 2],
  },
  (PV, default, Slack)={
    edge_index=[2, 3],
    edge_attr=[3, 5],
    edge_pq=[3, 2],
  },
  (Slack, default, PQ)={
    edge_index=[2, 3],
    edge_attr=[3, 5],
    edge_pq=[3, 2],
  },
  (Slack, default, PV)={
    edge_index=[2, 3],
    edge_attr=[3, 5],
    edge_pq=[3, 2],
  }
)

In [5]:
data, slices = torch.load('/mnt/afs/xupengyue/PoweFlowNet/data/processed/case118us_processed_test.pt')
data

Data(x=[57820, 4], edge_index=[2, 91140], edge_attr=[91140, 2], y=[57820, 4], bus_type=[57820], pred_mask=[57820, 4])

In [7]:
slices

defaultdict(dict,
            {'x': tensor([    0,   118,   236,   354,   472,   590,   708,   826,   944,  1062,
                      1180,  1298,  1416,  1534,  1652,  1770,  1888,  2006,  2124,  2242,
                      2360,  2478,  2596,  2714,  2832,  2950,  3068,  3186,  3304,  3422,
                      3540,  3658,  3776,  3894,  4012,  4130,  4248,  4366,  4484,  4602,
                      4720,  4838,  4956,  5074,  5192,  5310,  5428,  5546,  5664,  5782,
                      5900,  6018,  6136,  6254,  6372,  6490,  6608,  6726,  6844,  6962,
                      7080,  7198,  7316,  7434,  7552,  7670,  7788,  7906,  8024,  8142,
                      8260,  8378,  8496,  8614,  8732,  8850,  8968,  9086,  9204,  9322,
                      9440,  9558,  9676,  9794,  9912, 10030, 10148, 10266, 10384, 10502,
                     10620, 10738, 10856, 10974, 11092, 11210, 11328, 11446, 11564, 11682,
                     11800, 11918, 12036, 12154, 12272, 12390, 1250

In [6]:
data.x

tensor([[0.9190, -0.0000, 0.4782, 0.0000],
        [0.0000, -0.0000, 0.2588, 0.1224],
        [0.0000, -0.0000, 0.2927, 0.0956],
        ...,
        [1.0310, 0.0000, 2.1930, 0.0000],
        [0.0000, 0.0000, 0.1577, 0.1159],
        [0.0000, 0.0000, 0.4199, 0.0760]])

In [21]:
log_data = torch.load('./data/processed/case118v2_processed_test.pt')


In [22]:
log_data

(Data(x=[1062000, 4], edge_index=[2, 1674000], edge_attr=[1674000, 2], y=[1062000, 4], bus_type=[1062000], pred_mask=[1062000, 4]),
 {'x': tensor([      0,     118,     236,  ..., 1061764, 1061882, 1062000]),
  'edge_index': tensor([      0,     186,     372,  ..., 1673628, 1673814, 1674000]),
  'edge_attr': tensor([      0,     186,     372,  ..., 1673628, 1673814, 1674000]),
  'y': tensor([      0,     118,     236,  ..., 1061764, 1061882, 1062000]),
  'bus_type': tensor([      0,     118,     236,  ..., 1061764, 1061882, 1062000]),
  'pred_mask': tensor([      0,     118,     236,  ..., 1061764, 1061882, 1062000])})

In [4]:
log_data[1]['bus_type'].size()

torch.Size([9001])

In [4]:
log_data[1]['x'][:100]

tensor([    0,   118,   236,   354,   472,   590,   708,   826,   944,  1062,
         1180,  1298,  1416,  1534,  1652,  1770,  1888,  2006,  2124,  2242,
         2360,  2478,  2596,  2714,  2832,  2950,  3068,  3186,  3304,  3422,
         3540,  3658,  3776,  3894,  4012,  4130,  4248,  4366,  4484,  4602,
         4720,  4838,  4956,  5074,  5192,  5310,  5428,  5546,  5664,  5782,
         5900,  6018,  6136,  6254,  6372,  6490,  6608,  6726,  6844,  6962,
         7080,  7198,  7316,  7434,  7552,  7670,  7788,  7906,  8024,  8142,
         8260,  8378,  8496,  8614,  8732,  8850,  8968,  9086,  9204,  9322,
         9440,  9558,  9676,  9794,  9912, 10030, 10148, 10266, 10384, 10502,
        10620, 10738, 10856, 10974, 11092, 11210, 11328, 11446, 11564, 11682])

In [29]:
data3 = np.load('./data/raw/case118us_edge_features.npy')
data3.shape

(20000, 186, 4)

In [33]:
data3[:,:,0]

array([[ 0.,  0.,  3., ..., 11., 74., 75.],
       [ 0.,  0.,  3., ..., 11., 74., 75.],
       [ 0.,  0.,  3., ..., 11., 74., 75.],
       ...,
       [ 0.,  0.,  3., ..., 11., 74., 75.],
       [ 0.,  0.,  3., ..., 11., 74., 75.],
       [ 0.,  0.,  3., ..., 11., 74., 75.]])

In [23]:
data = np.load('./data/raw/case118us_node_features.npy')
data.shape

(20000, 118, 6)

In [27]:
data[:,:,2]

array([[1.09     , 0.9704446, 1.050271 , ..., 0.962    , 0.8961752,
        0.9195028],
       [0.953    , 0.963785 , 0.9798908, ..., 0.925    , 0.9688397,
        0.951248 ],
       [1.019    , 1.0219   , 1.004426 , ..., 0.944    , 1.026026 ,
        1.041495 ],
       ...,
       [1.036    , 0.9680392, 1.012739 , ..., 1.065    , 0.9163698,
        1.030571 ],
       [1.075    , 1.047964 , 1.051246 , ..., 1.045    , 1.015138 ,
        0.9902312],
       [0.908    , 0.9341401, 0.9885374, ..., 0.931    , 0.9414296,
        1.041738 ]])

In [9]:
data

array([[[  1.       ,   2.       ,   1.09     , -12.19864  ,
          69.62     ,  18.66     ],
        [  2.       ,   1.       ,   0.9704446,  -9.838718 ,
          22.87     ,  13.19     ],
        [  3.       ,   1.       ,   1.050271 ,  -9.95653  ,
          49.22     ,  11.01     ],
        ...,
        [116.       ,   2.       ,   0.962    ,  21.6115   ,
         148.4      ,   0.       ],
        [117.       ,   1.       ,   0.8961752,  -9.451343 ,
          24.84     ,   6.491    ],
        [118.       ,   1.       ,   0.9195028,  14.72615  ,
          39.28     ,  22.45     ]],

       [[  1.       ,   2.       ,   0.953    , -44.08498  ,
          72.93     ,  19.44     ],
        [  2.       ,   1.       ,   0.963785 , -38.78401  ,
          16.03     ,   5.862    ],
        [  3.       ,   1.       ,   0.9798908, -38.91525  ,
          46.95     ,   9.082    ],
        ...,
        [116.       ,   2.       ,   0.925    ,  22.5054   ,
         267.2      ,   0.       ],
  

In [32]:
# 读取 .npy 文件
data4 = np.load('./data/raw/case118v2_edge_features.npy')
data4[:,:,0]

array([[  0.,   0.,   3., ...,  80.,  86., 115.],
       [  0.,   0.,   3., ...,  80.,  86., 115.],
       [  0.,   0.,   3., ...,  80.,  86., 115.],
       ...,
       [  0.,   0.,   3., ...,  80.,  86., 115.],
       [  0.,   0.,   3., ...,  80.,  86., 115.],
       [  0.,   0.,   3., ...,  80.,  86., 115.]])

In [17]:
data4.shape

(30000, 186, 4)

In [16]:
len(data4)

30000

In [7]:
print(data4)

[[[0.00000000e+00 1.00000000e+00 3.60709165e-02 1.11527506e-01]
  [0.00000000e+00 2.00000000e+00 1.28334175e-02 4.36093139e-02]
  [3.00000000e+00 4.00000000e+00 1.60888136e-03 8.59817581e-03]
  ...
  [8.00000000e+01 7.90000000e+01 3.66300000e+01 0.00000000e+00]
  [8.60000000e+01 8.50000000e+01 2.05326000e+02 2.79972000e+01]
  [1.15000000e+02 6.70000000e+01 4.00950000e+00 3.36600000e-01]]

 [[0.00000000e+00 1.00000000e+00 3.51842684e-02 1.01697099e-01]
  [0.00000000e+00 2.00000000e+00 1.49628034e-02 4.94511315e-02]
  [3.00000000e+00 4.00000000e+00 1.86337380e-03 7.14801521e-03]
  ...
  [8.00000000e+01 7.90000000e+01 3.66300000e+01 0.00000000e+00]
  [8.60000000e+01 8.50000000e+01 2.05326000e+02 2.79972000e+01]
  [1.15000000e+02 6.70000000e+01 4.00950000e+00 3.36600000e-01]]

 [[0.00000000e+00 1.00000000e+00 2.73150204e-02 1.04822214e-01]
  [0.00000000e+00 2.00000000e+00 1.37688084e-02 4.98737628e-02]
  [3.00000000e+00 4.00000000e+00 1.63085563e-03 9.42060625e-03]
  ...
  [8.00000000e+01 

In [10]:
# 读取 .npy 文件
data2 = np.load('./data/raw/case118v2_node_features.npy')

In [11]:
data2.shape

(30000, 118, 6)

In [26]:
data2[:,:,1]

array([[1., 2., 2., ..., 1., 2., 2.],
       [1., 2., 2., ..., 1., 2., 2.],
       [1., 2., 2., ..., 1., 2., 2.],
       ...,
       [1., 2., 2., ..., 1., 2., 2.],
       [1., 2., 2., ..., 1., 2., 2.],
       [1., 2., 2., ..., 1., 2., 2.]])

In [20]:
len(data2)

30000

In [21]:
print(data2)

[[[ 0.00000000e+00  1.00000000e+00  1.04245776e+00  1.28424419e+01
    5.10389328e-01 -7.35313087e-01]
  [ 1.00000000e+00  2.00000000e+00  1.01949657e+00  1.36867641e+01
    2.13321197e-01  1.01122144e-01]
  [ 2.00000000e+00  2.00000000e+00  1.02737987e+00  1.42266111e+01
    3.30991331e-01  8.63436960e-02]
  ...
  [ 1.15000000e+02  1.00000000e+00  1.02220454e+00  2.75170605e+01
    1.64221771e+00 -1.34706937e+00]
  [ 1.16000000e+02  2.00000000e+00  9.97493780e-01  1.31814392e+01
    2.03995935e-01  7.33731915e-02]
  [ 1.17000000e+02  2.00000000e+00  1.00243113e+00  2.23078844e+01
    2.81584865e-01  1.21066671e-01]]

 [[ 0.00000000e+00  1.00000000e+00  1.02532955e+00  1.25768241e+01
    4.61335717e-01 -1.85554996e-01]
  [ 1.00000000e+00  2.00000000e+00  1.02690790e+00  1.31967392e+01
    2.04076142e-01  9.71324320e-02]
  [ 2.00000000e+00  2.00000000e+00  1.02278148e+00  1.36748237e+01
    3.60501859e-01  1.01276565e-01]
  ...
  [ 1.15000000e+02  1.00000000e+00  1.03882678e+00  2.73563

In [16]:
log_data_filter = torch.load('./data/processed/pre_filter.pt')
log_data_filter

'None'

In [18]:
log_data_transform = torch.load('./data/processed/pre_transform.pt')
log_data_transform

'None'

In [27]:
node_index = pd.DataFrame(data2[:,:,0])
node_index

0    1    2    3    4    5    6    7    8    9    ...    108    109  \
0      0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
1      0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
2      0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
3      0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
4      0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
29995  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
29996  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
29997  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
29998  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   
29999  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  ...  108.0  109.0   

         110    111    112    113    114    115    116    117  
0      110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
1      110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
2      110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
3      110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
4      110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
29995  110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
29996  110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
29997  110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
29998  110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  
29999  110.0  111.0  112.0  113.0  114.0  115.0  116.0  117.0  

[30000 rows x 118 columns]

In [28]:
node_type = pd.DataFrame(data2[:,:,1])
node_type

0    1    2    3    4    5    6    7    8    9    ...  108  109  110  \
0      1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
1      1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
2      1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
3      1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
4      1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
29995  1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
29996  1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
29997  1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
29998  1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   
29999  1.0  2.0  2.0  1.0  2.0  1.0  2.0  1.0  2.0  1.0  ...  2.0  1.0  1.0   

       111  112  113  114  115  116  117  
0      1.0  1.0  2.0  2.0  1.0  2.0  2.0  
1      1.0  1.0  2.0  2.0  1.0  2.0  2.0  
2      1.0  1.0  2.0  2.0  1.0  2.0  2.0  
3      1.0  1.0  2.0  2.0  1.0  2.0  2.0  
4      1.0  1.0  2.0  2.0  1.0  2.0  2.0  
...    ...  ...  ...  ...  ...  ...  ...  
29995  1.0  1.0  2.0  2.0  1.0  2.0  2.0  
29996  1.0  1.0  2.0  2.0  1.0  2.0  2.0  
29997  1.0  1.0  2.0  2.0  1.0  2.0  2.0  
29998  1.0  1.0  2.0  2.0  1.0  2.0  2.0  
29999  1.0  1.0  2.0  2.0  1.0  2.0  2.0  

[30000 rows x 118 columns]

In [34]:
(node_type == 3.0).sum().sum()

0

In [29]:
node_vm = pd.DataFrame(data2[:,:,2])
node_vm

0         1         2         3         4         5         6    \
0      1.042458  1.019497  1.027380  1.011260  1.015885  1.023764  1.019833   
1      1.025330  1.026908  1.022781  1.021160  1.024959  1.049418  1.044420   
2      1.042381  1.019499  1.027118  1.013125  1.024978  1.021567  1.018697   
3      1.007051  1.010051  1.008347  1.012602  1.022666  1.030311  1.026257   
4      1.041209  1.026501  1.033368  1.041085  1.038801  1.025398  1.025228   
...         ...       ...       ...       ...       ...       ...       ...   
29995  1.014237  1.009005  1.014815  1.039995  1.032711  1.035394  1.027083   
29996  1.006560  1.014710  1.010911  1.021403  1.026408  1.025260  1.026137   
29997  1.047610  1.021313  1.035702  1.029681  1.033554  1.032158  1.024732   
29998  1.025933  1.021283  1.019969  1.020798  1.023294  1.004208  1.013762   
29999  1.028907  1.028664  1.022285  1.014668  1.019274  1.017994  1.025698   

            7         8         9    ...       108       109       110  \
0      1.009750  1.008394  1.021648  ...  1.027494  1.023002  1.030310   
1      1.010801  1.021897  1.046266  ...  1.005757  1.003123  1.033051   
2      1.046836  1.022534  1.009407  ...  1.014445  1.019565  1.041885   
3      1.041029  1.025078  1.024448  ...  1.039077  1.049044  1.023003   
4      1.025430  1.027788  1.045701  ...  1.027279  1.044888  1.047236   
...         ...       ...       ...  ...       ...       ...       ...   
29995  1.004656  1.011326  1.031989  ...  1.034932  1.032772  1.011027   
29996  1.032724  1.007759  1.000879  ...  1.007864  1.009765  1.048594   
29997  1.039523  1.029035  1.021916  ...  1.009453  1.001486  1.022512   
29998  1.023364  1.010888  1.017604  ...  1.020730  1.024181  1.002826   
29999  1.015064  1.021246  1.049406  ...  1.004015  1.006883  1.024851   

            111       112       113       114       115       116       117  
0      1.038668  1.034148  1.016229  1.014166  1.022205  0.997494  1.002431  
1      1.035389  1.032875  1.038184  1.038133  1.038827  1.020892  1.004210  
2      1.045119  1.019949  1.030007  1.031770  1.010244  0.995949  1.003161  
3      1.010901  1.004244  1.005455  1.004747  1.020274  1.004206  1.012966  
4      1.031730  1.042579  1.011324  1.010231  1.009265  1.007644  1.018678  
...         ...       ...       ...       ...       ...       ...       ...  
29995  1.025351  1.046514  1.034256  1.033706  1.003857  0.995857  1.002775  
29996  1.010364  1.038509  1.022460  1.022726  1.005174  1.013437  1.023266  
29997  1.034074  1.005304  1.023552  1.023613  1.018107  0.994036  1.014172  
29998  1.034539  1.022470  1.016955  1.019616  1.032182  1.009959  1.019245  
29999  1.007086  1.035804  1.019534  1.020213  1.036905  1.022672  1.026227  

[30000 rows x 118 columns]

In [30]:
edge_frombus = pd.DataFrame(data[:,:,0])
edge_frombus

0    1    2    3    4    5    6    7    8    9    ...   176   177  \
0      0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
1      0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
2      0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
3      0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
4      0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
29995  0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
29996  0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
29997  0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
29998  0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   
29999  0.0  0.0  3.0  2.0  4.0  5.0  7.0  8.0  3.0  4.0  ...  37.0  62.0   

        178   179   180   181   182   183   184    185  
0      63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
1      63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
2      63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
3      63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
4      63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
...     ...   ...   ...   ...   ...   ...   ...    ...  
29995  63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
29996  63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
29997  63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
29998  63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  
29999  63.0  64.0  64.0  67.0  80.0  80.0  86.0  115.0  

[30000 rows x 186 columns]